# modules/report.rb
module Report
  def self.run
    print "Target: "
    target = gets.chomp
    print "Vulnerability: "
    vuln = gets.chomp
    print "Payload: "
    payload = gets.chomp

    report = <<~REPORT
      ==============================
            XPLORATOR REPORT
      ==============================

      Target: #{target}
      Vulnerability: #{vuln}
      Payload: #{payload}

      Generated by XPLORATOR CLI
    REPORT

    puts "\n#{report}"

    print "Save report? (y/n): "
    save = gets.chomp.downcase
    if save == 'y'
      filename = "report_#{Time.now.strftime('%Y%m%d%H%M%S')}.md"
      File.write(filename, report)
      puts "[*] Report saved as #{filename}"
    end

    puts "\n[*] Report generation selesai.\n\n"
  end
end
